datagrid:
    erp-accounts-grid:
        source:
            type: orm
            query:
                select:
                    - erp_accounts.id
                    - erp_accounts.accountOriginalId
                    - erp_accounts.firstName
                    - erp_accounts.lastName
                    - erp_accounts.email
                    - erp_accounts.originalEmail
                    - erp_accounts.websiteId
                    - erp_accounts.createdAt
                    - erp_accounts.updatedAt
                    - erp_accounts.created
                from:
                    - { table: DemacMediaErpBundle:OroErpAccounts, alias: erp_accounts }
        columns:
            accountOriginalId:
                label: demacmedia_erp.accounts.accountOriginalId.label
            firstName:
                label: demacmedia_erp.accounts.firstName.label
            lastName:
                label: demacmedia_erp.accounts.lastName.label
            email:
                label: demacmedia_erp.accounts.email.label
            originalEmail:
                label: demacmedia_erp.accounts.originalEmail.label
            websiteId:
                label: demacmedia_erp.accounts.websiteId.label
            createdAt:
                label: demacmedia_erp.accounts.createdAt.label
                frontend_type:    datetime
            updatedAt:
                label: demacmedia_erp.accounts.updatedAt.label
                frontend_type:    datetime
            created:
                label: demacmedia_erp.accounts.created.label
                frontend_type:    datetime

        sorters:
            columns:
                accountOriginalId:
                    data_name: erp_accounts.accountOriginalId
                firstName:
                    data_name: erp_accounts.firstName
                lastName:
                    data_name: erp_accounts.lastName
                email:
                    data_name: erp_accounts.email
                originalEmail:
                    data_name: erp_accounts.originalEmail
                websiteId:
                    data_name: erp_accounts.websiteId
                createdAt:
                    data_name: erp_accounts.createdAt
                updatedAt:
                    data_name: erp_accounts.updatedAt
                created:
                    data_name: erp_accounts.created
            default:
                id: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      demacmedia_erp_accounts_view
                params:     [ originalEmail ]

        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                rowAction:    true

        filters:
            columns:
                accountOriginalId:
                    type: number
                    data_name: erp_accounts.accountOriginalId
                firstName:
                    type: string
                    data_name: erp_accounts.firstName
                lastName:
                    type: string
                    data_name: erp_accounts.lastName
                email:
                    type: string
                    data_name: erp_accounts.email
                originalEmail:
                    type: string
                    data_name: erp_accounts.originalEmail
                websiteId:
                    type: string
                    data_name: erp_accounts.websiteId
                createdAt:
                    type: datetime
                    data_name: erp_accounts.createdAt
                updatedAt:
                    type: datetime
                    data_name: erp_accounts.updatedAt
                created:
                    type: datetime
                    data_name: erp_accounts.created

    # ORDERS
    ############################################################
    erp-orders-grid:
        source:
            type: orm
            query:
                select:
                    - erp_orders.id
                    - erp_orders.originalOrderId
                    - IDENTITY(erp_orders.originalEmail) as originalEmail
                    - erp_orders.totalPaid
                    - erp_orders.createdAt
                    - erp_orders.updatedAt
                    - erp_orders.created
                    - erp_accounts.firstName
                    - erp_accounts.lastName
                from:
                    - { table: DemacMediaErpBundle:OroErpOrders, alias: erp_orders }
                join:
                    inner:
                        -
                            join: DemacMediaErpBundle:OroErpAccounts
                            alias: erp_accounts
                            conditionType: WITH
                            condition: erp_accounts.originalEmail = erp_orders.originalEmail

        columns:
            originalOrderId:
                label: demacmedia_erp.orders.originalOrderId.label
            originalEmail:
                label: demacmedia_erp.orders.originalEmail.label
            totalPaid:
                label: demacmedia_erp.orders.totalPaid.label
                frontend_type: currency
            firstName:
                label: demacmedia_erp.accounts.firstName.label
            lastName:
                label: demacmedia_erp.accounts.lastName.label
            createdAt:
                label: demacmedia_erp.orders.createdAt.label
                frontend_type: datetime
            updatedAt:
                label: demacmedia_erp.orders.updatedAt.label
                frontend_type: datetime
            created:
                label: demacmedia_erp.orders.created.label
                frontend_type: datetime

        sorters:
            columns:
                originalOrderId:
                    data_name: erp_orders.originalOrderId
                originalOrderId:
                    data_name: erp_orders.originalEmail
                totalPaid:
                    data_name: erp_orders.totalPaid
                firstName:
                    data_name: erp_accounts.firstName
                lastName:
                    data_name: erp_accounts.lastName
                createdAt:
                    data_name: erp_orders.createdAt
                updatedAt:
                    data_name: erp_orders.updatedAt
                created:
                    data_name: erp_orders.created
            default:
                id: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      demacmedia_erp_orders_view
                params:     [ originalOrderId ]

        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                rowAction:    true

        filters:
            columns:
                originalOrderId:
                    type: string
                    data_name: erp_orders.originalOrderId
                originalOrderId:
                    type: string
                    data_name: erp_orders.originalOrderId
                totalPaid:
                    type: currency
                    data_name: erp_orders.totalPaid
                firstName:
                    type: string
                    data_name: erp_accounts.firstName
                lastName:
                    type: string
                    data_name: erp_accounts.lastName
                createdAt:
                    type: string
                    data_name: erp_orders.createdAt
                updatedAt:
                    type: string
                    data_name: erp_orders.updatedAt
                created:
                    type: datetime
                    data_name: erp_orders.created

    # ORDERS FOR SPECIFIC ACCOUNT
    ############################################################
    erp-orders-specific-grid:
        source:
            type: orm
            query:
                select:
                    - erp_orders.id
                    - erp_orders.originalOrderId
                    - IDENTITY(erp_orders.originalEmail) as originalEmail
                    - erp_orders.totalPaid
                    - erp_orders.createdAt
                    - erp_orders.updatedAt
                    - erp_orders.created
                from:
                    - { table: DemacMediaErpBundle:OroErpOrders, alias: erp_orders }
                where:
                    and:
                        - IDENTITY(erp_orders.originalEmail) IN (:original_email)
            bind_parameters:
                original_email: original_email

        columns:
            originalOrderId:
                label: demacmedia_erp.orders.originalOrderId.label
            originalEmail:
                label: demacmedia_erp.orders.originalEmail.label
            totalPaid:
                label: demacmedia_erp.orders.totalPaid.label
                frontend_type: currency
            createdAt:
                label: demacmedia_erp.orders.createdAt.label
                frontend_type: datetime
            updatedAt:
                label: demacmedia_erp.orders.updatedAt.label
                frontend_type: datetime
            created:
                label: demacmedia_erp.orders.created.label
                frontend_type: datetime

        sorters:
            columns:
                originalOrderId:
                    data_name: erp_orders.originalOrderId
                originalEmail:
                    data_name: erp_orders.originalEmail
                totalPaid:
                    data_name: erp_orders.totalPaid
                createdAt:
                    data_name: erp_orders.createdAt
                updatedAt:
                    data_name: erp_orders.updatedAt
                created:
                    data_name: erp_orders.created
            default:
                id: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      demacmedia_erp_orders_view
                params:     [ originalOrderId ]

        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                rowAction:    true

        filters:
            columns:
                originalOrderId:
                    type: number
                    data_name: erp_orders.originalOrderId
                originalEmail:
                    type: string
                    data_name: erp_orders.originalEmail
                totalPaid:
                    type: currency
                    data_name: erp_orders.totalPaid
                createdAt:
                    type: datetime
                    data_name: erp_orders.createdAt
                updatedAt:
                    type: datetime
                    data_name: erp_orders.updatedAt
                created:
                    type: datetime
                    data_name: erp_orders.created



    erp-order-items-grid:
        source:
            type: orm
            query:
                select:
                    - erp_order_items.id
                    - erp_order_items.originalOrderItemId
                    - IDENTITY(erp_order_items.orderId) as orderId
                    - erp_order_items.sku
                    - erp_order_items.productName
                    - erp_order_items.productPrice
                    - erp_order_items.quantity
                    - erp_order_items.createdAt
                    - erp_order_items.updatedAt
                    - erp_order_items.updated
                from:
                    - { table: DemacMediaErpBundle:OroErpOrderItems, alias: erp_order_items }
                where:
                    and:
                        - IDENTITY(erp_order_items.orderId) = :order_id
            bind_parameters:
                order_id: order_id

        columns:
            originalOrderItemId:
                label: demacmedia_erp.order_items.originalOrderItemId.label
            orderId:
                label: demacmedia_erp.order_items.orderId.label
            sku:
                label: demacmedia_erp.order_items.sku.label
            productName:
                label: demacmedia_erp.order_items.productName.label
                frontend_type: currency
            productPrice:
                label: demacmedia_erp.order_items.productPrice.label
                frontend_type: currency
            quantity:
                label: demacmedia_erp.order_items.quantity.label
            createdAt:
                label: demacmedia_erp.order_items.createdAt.label
                frontend_type: datetime
            updatedAt:
                label: demacmedia_erp.order_items.updatedAt.label
                frontend_type: datetime
            updated:
                label: demacmedia_erp.order_items.updated.label
                frontend_type: datetime

        sorters:
            columns:
                originalOrderItemId:
                    data_name: erp_order_items.originalOrderItemId
                orderId:
                    data_name: erp_order_items.orderId
                sku:
                    data_name: erp_order_items.sku
                productName:
                    data_name: erp_order_items.productName
                productPrice:
                    data_name: erp_order_items.productPrice
                quantity:
                    data_name: erp_order_items.quantity
                createdAt:
                    data_name: erp_order_items.createdAt
                updatedAt:
                    data_name: erp_order_items.updatedAt
                updated:
                    data_name: erp_order_items.updated

            default:
                id: DESC

        filters:
            columns:
                originalOrderItemId:
                    type: number
                    data_name: erp_order_items.originalOrderItemId
                orderId:
                    type: number
                    data_name: erp_order_items.orderId
                sku:
                    type: string
                    data_name: erp_order_items.sku
                productName:
                    type: string
                    data_name: erp_order_items.productName
                productPrice:
                    type: currency
                    data_name: erp_order_items.productPrice
                quantity:
                    type: number
                    data_name: erp_order_items.quantity
                createdAt:
                    type: datetime
                    data_name: erp_order_items.createdAt
                updatedAt:
                    type: datetime
                    data_name: erp_order_items.updatedAt
                updated:
                    type: datetime
                    data_name: erp_order_items.updated


