oro_entity:
    virtual_fields:
        Oro\Bundle\AccountBundle\Entity\Account:
            number_of_orders_value:
                query:
                    select:
                        expr:         oro_erp_accounts.number_of_orders_all
                        return_type:  string
                    join:
                        left:
                            - { join: 'DemacMediaErpBundle:OroErpAccounts', alias: 'oro_erp_accounts', conditionType: 'WITH', condition: 'oro_erp_accounts.account = entity' }