placeholders:
    view_content_data_additional_information:
        items:
            demacmedia_instore_orders: ~

items:
    demacmedia_instore_orders:
        template: DemacMediaErpBundle:Default:orders-specific-view-accounts.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)

