definitions:
    instore_customer_creation:
        label:   'Create Account and Contact for WebStore Customer'
        enabled: true
        entity:  DemacMedia\Bundle\ErpBundle\Entity\OroErpAccounts # Entity the data is comming from.
        order:   10
        exclude_definitions: [instore_customer_creation] # Protect from overlapping triggering before this finish.
        actions_configuration:
            - @tree: # Main Process Logic lives inside here

                # Same email, different names:
                # It must share the same OroAccount and OroContact
                #
                # A@A.com   website-1   name-A
                # A@A.com   website-2   name-B
                #
                # -----------------------------------------------------------
                # Different email and different name,
                # It must create a new account for each one
                #
                # A@A.com   website-1   name-A
                # B@B.com   website-2   name-B
                #
                # -----------------------------------------------------------
                # Same email, same names:
                # It must share the same OroAccount and OroContact
                #
                # A@A.com   website-1   name-A
                # A@A.com   website-2   name-A

                actions:
                    - @assign_value:
                        attribute: $.emailToMatch # Now any reference to email will be using this variable name
                        value: $email
                    - @format_string:
                        attribute: $.contactName # Contact Name now is referenced by this variable
                        string: '%first_name% %last_name%'
                        arguments:
                            first_name: $firstName
                            last_name: $lastName


                    # Try to find any Contact with the same $email from WebAccounts
                    - @find_entity:
                        parameters:
                            class: OroCRM\Bundle\ContactBundle\Entity\Contact
                            attribute: $.findContactByEmail  # Stores the result if the "find_entity" here.
                            where:
                                email: $.emailToMatch


                    # Tries to find OroAccount from the contact above ^
                    - @find_entity:
                        conditions:
                        # If the previous "find_entity" found a contact with the same email,
                        # It gets the AccountId from this contact.
                            @not_empty: $.findContactByEmail
                        parameters:
                            class: OroCRM\Bundle\AccountBundle\Entity\Account
                            attribute: $.findAccountByContactEmail  # Store the result here
                            where:
                                # name: $.contactName # If there is no contactName, gets
                                defaultContact: $.findContactByEmail.id

                    ################################################################
                    - @find_entity:
                        parameters:
                            class: OroCRM\Bundle\ContactBundle\Entity\Source
                            attribute: $.instore
                            where:
                                name: 'instore'
                    #---------------------------------------------------------------------------
                    - @tree:
                        conditions:
                            @and:
                                - @empty: $.findContactByEmail
                                - @empty: $.findAccountByContactEmail
                            # If there are no

                        actions:
                            - @create_entity: # create Contact
                                class:     OroCRM\Bundle\ContactBundle\Entity\Contact
                                attribute: $contact
                                data:
                                    email:        $email
                                    firstName:    $firstName
                                    lastName:     $lastName
                                    source:       $.instore
                                    owner:        $owner
                                    organization: $organization
                            - @create_entity: # create Contact Address
                                class:     OroCRM\Bundle\ContactBundle\Entity\ContactAddress
                                attribute: $.contactAddress
                                data:
                                    street:       $address1
                                    street2:      $address2
                                    city:         $city
                                    postalCode:   $zip
                                    organization: $organization
                                    firstName:    $firstName
                            - @call_method: # add Contact Address to Contact
                                object: $contact
                                method: addAddress
                                method_parameters: [$.contactAddress]
                            - @tree: # add Contact Phone
                                  conditions:
                                      @not_empty: $phone
                                  actions:
                                      - @create_entity: # create Contact phone
                                          class:     OroCRM\Bundle\ContactBundle\Entity\ContactPhone
                                          attribute: $.contactPhone
                                          data:
                                              phone:   $phone
                                              primary: $phone2
                                      - @call_method: # add Contact Phone to Contact
                                          object: $contact
                                          method: addPhone
                                          method_parameters: [$.contactPhone]
                            - @tree: # add Contact Email
                                conditions:
                                    @not_empty: $email
                                actions:
                                    - @create_entity: # create Contact Email
                                        class:     OroCRM\Bundle\ContactBundle\Entity\ContactEmail
                                        attribute: $.contactEmail
                                        data:
                                            email:   $email
                                            primary: true
                                    - @call_method: # add Contact Email to Contact
                                        object: $contact
                                        method: addEmail
                                        method_parameters: [$.contactEmail]
                                    - @unset_value: [$.contactEmail]

                        # actions:
                            - @create_entity: # create Account
                                conditions: # if Account does not exist
                                   @empty: $account
                                parameters:
                                    class:     OroCRM\Bundle\AccountBundle\Entity\Account
                                    attribute: $account
                                    data:
                                        defaultContact: $contact
                                        name:           $.contactName
                                        owner:          $owner
                                        organization:   $organization
                    - @call_method: # connect in-Store Customer with Contact by Email
                        conditions:
                            @not_empty: $.findContactByEmail
                        parameters:
                            object: $.data # this is the current entity!
                            method: setContact
                            method_parameters: [$.findContactByEmail]
                    - @call_method: # connect in-Store Customer with Account by Name
                        conditions:
                            @not_empty: $.findAccountByContactEmail
                        parameters:
                            object: $.data # this is the current entity!
                            method: setAccount
                            method_parameters: [$.findAccountByContactEmail]
triggers:
    instore_customer_creation:
        -
            event:    create
            priority: 5
            queued:   true  # put it on job queue!
        -
            event:    update
            priority: 5
            queued:   true  # put it on job queue!

