parameters:
    demacmedia_erp_accounts.entity.class:         DemacMedia\Bundle\ErpBundle\Entity\OroErpAccounts
    demacmedia_erp_orders.entity.class:           DemacMedia\Bundle\ErpBundle\Entity\OroErpOrders
    demacmedia_erp_orderitems.entity.class:       DemacMedia\Bundle\ErpBundle\Entity\OroErpOrderItems
    demacmedia_erp_carts.entity.class:            DemacMedia\Bundle\ErpBundle\Entity\OroErpCarts
    demacmedia_erp_cartitems.entity.class:        DemacMedia\Bundle\ErpBundle\Entity\OroErpCartItems
    demacmedia_erp.manager.api.class:             Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    demacmedia_erp.demac_assign_entity.action.class:    DemacMedia\Bundle\ErpBundle\Model\Action\AssignEntity
    demacmedia_erp_orderitems.ordem_items.listener.class: DemacMedia\Bundle\ErpBundle\EventListener\OriginalEmailListener
    demacmedia_erp.formevent.class:               Oro\Bundle\FormBundle\Event\FormHandler\FormProcessEvent
    demacmedia_erp.provider.erp_channel_type.class:    DemacMedia\Bundle\ErpBundle\Provider\ErpChannelType
    demacmedia_erp.provider.customer_identification.class: DemacMedia\Bundle\ErpBundle\Provider\CustomerIdentification
    demacmedia_erp.lifetime_helper.class:         DemacMedia\Bundle\ErpBundle\Entity\Helper\OroErpAccountsHelper
    demacmedia_erp.update_lifetime.listener.class: DemacMedia\Bundle\ErpBundle\EventListener\UpdateLifetimeSalesValueListener

services:
    # CHANNEL REGISTRATION PROVIDER
    demacmedia_erp.provider.erp_channel_type:
        class: %demacmedia_erp.provider.erp_channel_type.class%
        tags:
            - { name: oro_integration.channel, type: erp }


    # ACCOUNTS
    demacmedia_erp_accounts.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %demacmedia_erp_accounts.entity.class%
            - @doctrine.orm.entity_manager

    # ORDERS
    demacmedia_erp_orders.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
        - %demacmedia_erp_orders.entity.class%
        - @doctrine.orm.entity_manager


    # ORDER ITEMS
    demacmedia_erp_orderitems.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
        - %demacmedia_erp_orderitems.entity.class%
        - @doctrine.orm.entity_manager

    # CARTS
    demacmedia_erp_carts.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
        - %demacmedia_erp_carts.entity.class%
        - @doctrine.orm.entity_manager


    # CART ITEMS
    demacmedia_erp_cartitems.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
        - %demacmedia_erp_cartitems.entity.class%
        - @doctrine.orm.entity_manager

    # Custom Tracking Customer Identification WebAccounts
    demacmedia_erp.provider.customer_identification:
        class: %demacmedia_erp.provider.customer_identification.class%
        arguments:
           - "@doctrine"
           - "@oro_entity_config.provider.extend"
           - "@orocrm_channel.provider.settings_provider"
        tags:
           - { name: oro_tracking.provider.identification, priority: 10 }

    # Lifetime Helper
    demacmedia_erp.lifetime_helper:
        class: %demacmedia_erp.lifetime_helper.class%
        arguments:
          - @doctrine.orm.entity_manager

    # EventListener to update Lifetime Sales Value on every update/insert (orders)
    demacmedia_erp.update_lifetime.listener:
        class: %demacmedia_erp.update_lifetime.listener.class%
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: postPersist, connection: default }
