parameters:
    demacmedia_erp_accounts.entity.class:         DemacMedia\Bundle\ErpBundle\Entity\OroErpAccounts
    demacmedia_erp_orders.entity.class:           DemacMedia\Bundle\ErpBundle\Entity\OroErpOrders
    demacmedia_erp_orderitems.entity.class:       DemacMedia\Bundle\ErpBundle\Entity\OroErpOrderItems
    demacmedia_erp.manager.api.class:             Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    demacmedia_erp.demac_assign_entity.action.class:    DemacMedia\Bundle\ErpBundle\Model\Action\AssignEntity
    demacmedia_erp_orderitems.ordem_items.listener.class: DemacMedia\Bundle\ErpBundle\EventListener\OriginalEmailListener
    demacmedia_erp.formevent.class:               Oro\Bundle\FormBundle\Event\FormHandler\FormProcessEvent

services:
    # ACCOUNTS
    demacmedia_erp_accounts.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %demacmedia_erp_accounts.entity.class%
            - @doctrine.orm.entity_manager


    # ORDERS
    demacmedia_erp_orders.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
        - %demacmedia_erp_orders.entity.class%
        - @doctrine.orm.entity_manager


    # ORDER ITEMS
    demacmedia_erp_orderitems.manager.api:
        class: %demacmedia_erp.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
        - %demacmedia_erp_orderitems.entity.class%
        - @doctrine.orm.entity_manager

